### ISSUE TITLE
How do you transform the chat completions to the numerical sequnces?

### ISSUE THREAD

**Issue by Ytang520** [AdityaLab/lstprompt#3]
Hi, I noticed that you have released the code and found that you only modified the 'extra_input' in the gpt.py (Please correct me if I was wrong).When testing on the ETTh1 dataset, I obtained the following completions using your code:

"Sure! Let's start by breaking down the task into short-term and long-term predictions. \n\n**Short-term prediction:**\nFor short-term predictions, we will focus on trends and the last few steps of the input sequence to forecast the immediate future.\n\n**Long-term prediction:**\nFor long-term predictions, we will emphasize cyclical patterns and statistical properties of the entire input sequence to forecast further into the future.\n\nLet's begin with short-term predictions:\n\n**Short-term Prediction Mechanism:**\nTo predict the immediate future, we will use a simple moving average approach that considers the trends in the last few time steps. We will calculate the average of the last 5 time steps and use it as the prediction for the next time step.\n\n**Short-term Predictions:**\n1. Short-term prediction: 1223\n2. Short-term prediction: 1186\n3. Short-term prediction: 1211\n4. Short-term prediction: 1174\n5. Short-term prediction: 1074\n\nNow, take a deep breath before we move on to long-term predictions.\n\n*Deep breath*\n\n**Long-term Prediction Mechanism:**\nFor long-term predictions, we will use a seasonal decomposition of time series (STL) approach to extract the seasonal component and predict future values based on cyclical patterns.\n\n**Long-term Predictions:**\n1. Long-term prediction: 942\n2. Long-term prediction: 915\n3. Long-term prediction: 890\n4. Long-term prediction: 865\n5. Long-term prediction: 837\n\n*Deep breath*\n\nI hope these predictions help! Let me know if you need any further assistance."

I am curious about the process you use to transform chat completions into numerical sequences. Additionally, could you share the logs from your code execution? This might help us better understand any potential misunderstandings within the code.

Many thanks!

**Comment by haoxin1998** [comment]
Hi, our code is based on llmtime. There are other modifications, including the discarding of outliers and the way of numerical preprocessing. This is a common phenomenon. There are some randomness in the gpt api and it also occurs when llmtime is running. One way to deal with this is to perform post-processing to extract the numerical sequence. Since the setting of llmtime only tests the last use case, I did not write specific extraction code. Would you like to share the detail code how you use it on ETT when this happens (email: hliu763@gatech.edu)?
